library(dada2); library(tidyverse)
dadaFs <- dada(filtFs, err = errF, multithread = FALSE)
dadaRs <- dada(filtRs, err = errR, multithread = FALSE)
print("Forward Read Inference for Sample 1:")
print(dadaFs[[1]])
mergers <- mergePairs(dadaFs, filtFs, dadaRs, filtRs, verbose=TRUE)
head(mergers[[1]])
seqtab <- makeSequenceTable(mergers)
dim(seqtab)
seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=FALSE, verbose=TRUE)

real_proportion <- sum(seqtab.nochim) / sum(seqtab)
print(paste("Proportion of clean sequences retained:", round(real_proportion * 100, 2), "%"))